#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src

COPY ["containers/api-sac/src/SGM.SAC.Api.csproj", "containers/api-sac/src/"]
COPY ["dotnet-packages/sac/src/SGM.SAC.Domain/SGM.SAC.Domain.csproj", "dotnet-packages/sac/src/SGM.SAC.Domain/"]
COPY ["dotnet-packages/sac/src/SGM.SAC.Infra.Crosscutting/SGM.SAC.Infra.Crosscutting.csproj", "dotnet-packages/sac/src/SGM.SAC.Infra.Crosscutting/"]
COPY ["dotnet-packages/sac/src/SGM.SAC.Infra.Data/SGM.SAC.Infra.Data.csproj", "dotnet-packages/sac/src/SGM.SAC.Infra.Data/"]


RUN dotnet restore "containers/api-sac/src/SGM.SAC.Api.csproj"
COPY . .
WORKDIR "/src/containers/api-sac/src"
RUN dotnet build "SGM.SAC.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SGM.SAC.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SGM.SAC.Api.dll"]
