version: '3'
        
services:
    sgm-sac-api:
        image: sgm-sac-api:latest
        container_name: sgm-sac-api   
        ports:
            - "5005:80"        
        build:
            context: .
            dockerfile: ./dockerfile-api
            
        environment:
            - ASPNETCORE_ENVIRONMENT=Development